services:
  dev_env:
    build: 
      context: .
      args:
        - WORKING_DIR=$WORKING_DIR
        - GRP_ID=$GRP_ID
        - USER_ID=$USER_ID
        - USER_NAME=$USER_NAME
    image: vscode-server
    user: ${USER_ID}:${GRP_ID}
    ports:
      - $PORT:$VS_PORT
    environment:
      - SSH_AUTH_SOCK:${SSH_AUTH_SOCK}
    volumes:
      - $WDIR:$WORKING_DIR
      - ${SSH_KEY}:/home/${USER_NAME}/.ssh/id_git
    working_dir: $WORKING_DIR
    command: [ "/opt/vscode-server/start_code_server.sh", $OPTIONS ]
